# [deep-ml.com](https://www.deep-ml.com/problems)

# Matrix times Vector

Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

In [1]:
def matrix_dot_vector(a, b):
    if len(a) != len(b):
        c = -1
    else:
        c = [0] * len(a)
        for i in range(len(a)):
            for j in range(len(a[i])):
                c[i] += a[i][j] * b[j]
    return c

In [2]:
a = [1, 2, 3], [2, 4, 5], [6, 8, 9]
b = [1, 2, 3]

In [3]:
matrix_dot_vector(a, b)

[14, 25, 49]

# Transpose of Matrix
Write a Python function that computes the transpose of a given matrix.

In [4]:
def transpose_matrix(a):
    rows = len(a)
    cols = len(a[0])

    b = [[0 for _ in range(rows)] for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            b[j][i] = a[i][j]

    return b

In [5]:
a = [[1, 2, 3], [4, 5, 6]]

In [6]:
transpose_matrix(a)

[[1, 4], [2, 5], [3, 6]]

# Reshape Matrix
Write a Python function that reshapes a given matrix into a specified shape.

In [7]:
import numpy as np

In [8]:
def reshape_matrix(a, new_shape):
    a = np.array(a)
    reshaped_matrix = a.reshape(*new_shape)
    return reshaped_matrix.tolist()

In [9]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]]
new_shape = (4, 2)

In [10]:
reshape_matrix(a, new_shape)

[[1, 2], [3, 4], [5, 6], [7, 8]]

# Calculate Mean by Row or Column
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

In [11]:
def calculate_matrix_mean(matrix, mode):

    means = []

    if mode == "column":
        mask = [[0 for _ in range(len(matrix))] for _ in range(len(matrix[0]))]

        for col in range(len(matrix[0])):
            for row in range(len(matrix)):
                mask[row][col] = matrix[col][row]
        for col in range(len(mask[0])):
            means.append(sum(mask[col]) / len(mask[0]))

    else:
        for row in range(len(matrix)):
            means.append(sum(matrix[row]) / len(matrix[0]))

    return means

In [12]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mode = "column"

In [13]:
calculate_matrix_mean(matrix, mode="column")

[4.0, 5.0, 6.0]

# Scalar Multiplication of a Matrix
Write a Python function that multiplies a matrix by a scalar and returns the result.

In [14]:
matrix = [[1, 2], [3, 4]]
scalar = 2

In [15]:
def scalar_multiply(matrix, scalar):
    result = [[0 for _ in range(len(matrix))] for _ in range(len(matrix[0]))]
    for i in range(len(matrix[0])):
        for j in range(len(matrix)):
            result[i][j] = matrix[i][j] * scalar
    return result

In [16]:
scalar_multiply(matrix, scalar)

[[2, 4], [6, 8]]

# Calculate Covariance Matrix
Write a Python function to calculate the covariance matrix for a given set of vectors. The function should take a list of lists, where each inner list represents a feature with its observations, and return a covariance matrix as a list of lists. Additionally, provide test cases to verify the correctness of your implementation.

In [48]:
vectors = [[1, 2, 3], [4, 5, 6]]

In [59]:
def calculate_covariance_matrix(vectors):

	n = len(vectors)
	m = len(vectors[0])

	сvectors = [[0 for _ in range(n)] for _ in range(n)]
	means = [sum(vectors[i])/m for i in range(n)]

	for i in range(n):
		for j in range(i, n):
			covariance = sum((vectors[i][k] - means[i]) * (vectors[j][k] - means[j]) for k in range(m)) / (m - 1)
			сvectors[i][j] = сvectors[j][i] = covariance

	return сvectors

In [60]:
calculate_covariance_matrix(vectors)

[[1.0, 1.0], [1.0, 1.0]]

# Linear Regression Using Normal Equation
Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

In [61]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [121]:
import numpy as np
def linear_regression_normal_equation(X, y):
    X, y = np.array(X), np.array(y)
    theta = np.round(((np.linalg.inv(X.T@X))@X.T@y), 3)
    return theta

In [122]:
linear_regression_normal_equation(X,y)

array([-0.,  1.])

# Linear Regression Using Gradient Descent
Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.

In [44]:
import numpy as np

X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
alpha = 0.01
iterations = 1000

In [45]:
def linear_regression_gradient_descent(X: np.ndarray, y: np.ndarray, alpha: float, iterations: int) -> np.ndarray:

	m, n = X.shape
	theta = np.zeros((n, 1))

	for iter in range(iterations):
		preds = X @ theta
		error = preds - y.reshape(-1,1)

		upd = X.T @ error / m
		
		theta -= alpha*upd
	
	theta = np.round(theta.flatten(), 4)
	return theta

In [46]:
linear_regression_gradient_descent(X, y, alpha, iterations)

array([0.1107, 0.9513])

# Feature Scaling Implementation
Write a Python function that performs feature scaling on a dataset using both standardization and min-max normalization. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. It should return two 2D NumPy arrays: one scaled by standardization and one by min-max normalization. Make sure all results are rounded to the nearest 4th decimal.



In [149]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [150]:
import numpy as np

In [179]:
def feature_scaling(data: np.ndarray) -> (np.ndarray, np.ndarray):

	standardized_data = (data - data.mean(axis = 0)) / data.std(axis = 0)
	normalized_data = ((data - data.min(axis = 0))/ (data.max(axis = 0) - data.min(axis = 0)))

	return np.round(standardized_data, 4), np.round(normalized_data ,4)

In [180]:
feature_scaling(data)

(array([[-1.2247, -1.2247],
        [ 0.    ,  0.    ],
        [ 1.2247,  1.2247]]),
 array([[0. , 0. ],
        [0.5, 0.5],
        [1. , 1. ]]))

# Sigmoid Activation Function Understanding

Write a Python function that computes the output of the sigmoid activation function given an input value z. The function should return the output rounded to four decimal places.

In [61]:
z = 0

In [62]:
import math

def sigmoid(z: float) -> float:
	sigma = 1 / (1+math.exp(-z))
	return round(sigma, 4)

In [63]:
sigmoid(z)

0.5

# Batch Iterator for Dataset

In [64]:
import numpy as np

X = np.array([[1, 2], 
              [3, 4], 
              [5, 6], 
              [7, 8], 
              [9, 10]])

y = np.array([1, 2, 3, 4, 5])

batch_size = 2

In [65]:
def batch_iterator(X, y, batch_size):
    
    samples = X.shape[0]
    batches = []

    for i in np.arange(0, samples, batch_size):
        begin, end = i, min(i+batch_size, samples)
        
        if y is not None:
            batches.append([X[begin:end], y[begin:end]])
        else:
            batches.append(X[begin:end])

    return batches

In [66]:
batch_iterator(X, y, batch_size)

[[array([[1, 2],
         [3, 4]]),
  array([1, 2])],
 [array([[5, 6],
         [7, 8]]),
  array([3, 4])],
 [array([[ 9, 10]]), array([5])]]