# [deep-ml.com](https://www.deep-ml.com/problems)

# Matrix times Vector

Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

In [88]:
def matrix_dot_vector(a, b):
    if len(a) != len(b):
        c = -1
    else:
        c = [0] * len(a)
        for i in range(len(a)):
            for j in range(len(a[i])):
                c[i] += a[i][j] * b[j]
    return c

In [89]:
a = [1, 2, 3], [2, 4, 5], [6, 8, 9]
b = [1, 2, 3]

In [90]:
matrix_dot_vector(a, b)

[14, 25, 49]

# Transpose of Matrix
Write a Python function that computes the transpose of a given matrix.

In [91]:
def transpose_matrix(a):
    rows = len(a)
    cols = len(a[0])

    b = [[0 for _ in range(rows)] for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            b[j][i] = a[i][j]

    return b

In [92]:
a = [[1, 2, 3], [4, 5, 6]]

In [93]:
transpose_matrix(a)

[[1, 4], [2, 5], [3, 6]]

# Reshape Matrix
Write a Python function that reshapes a given matrix into a specified shape.

In [94]:
import numpy as np

In [95]:
def reshape_matrix(a, new_shape):
    a = np.array(a)
    reshaped_matrix = a.reshape(*new_shape)
    return reshaped_matrix.tolist()

In [96]:
a = [[1, 2, 3, 4], [5, 6, 7, 8]]
new_shape = (4, 2)

In [97]:
reshape_matrix(a, new_shape)

[[1, 2], [3, 4], [5, 6], [7, 8]]

# Calculate Mean by Row or Column
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

In [98]:
def calculate_matrix_mean(matrix, mode):

    means = []

    if mode == "column":
        mask = [[0 for _ in range(len(matrix))] for _ in range(len(matrix[0]))]

        for col in range(len(matrix[0])):
            for row in range(len(matrix)):
                mask[row][col] = matrix[col][row]
        for col in range(len(mask[0])):
            means.append(sum(mask[col]) / len(mask[0]))

    else:
        for row in range(len(matrix)):
            means.append(sum(matrix[row]) / len(matrix[0]))

    return means

In [99]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mode = "column"

In [100]:
calculate_matrix_mean(matrix, mode="column")

[4.0, 5.0, 6.0]

# Scalar Multiplication of a Matrix
Write a Python function that multiplies a matrix by a scalar and returns the result.

In [101]:
matrix = [[1, 2], [3, 4]]
scalar = 2

In [102]:
def scalar_multiply(matrix, scalar):
    result = [[0 for _ in range(len(matrix))] for _ in range(len(matrix[0]))]
    for i in range(len(matrix[0])):
        for j in range(len(matrix)):
            result[i][j] = matrix[i][j] * scalar
    return result

In [103]:
scalar_multiply(matrix, scalar)

[[2, 4], [6, 8]]

# Calculate Covariance Matrix
Write a Python function to calculate the covariance matrix for a given set of vectors. The function should take a list of lists, where each inner list represents a feature with its observations, and return a covariance matrix as a list of lists. Additionally, provide test cases to verify the correctness of your implementation.

In [104]:
vectors = [[1, 2, 3], [4, 5, 6]]

In [105]:
def calculate_covariance_matrix(vectors):

	n = len(vectors)
	m = len(vectors[0])

	сvectors = [[0 for _ in range(n)] for _ in range(n)]
	means = [sum(vectors[i])/m for i in range(n)]

	for i in range(n):
		for j in range(i, n):
			covariance = sum((vectors[i][k] - means[i]) * (vectors[j][k] - means[j]) for k in range(m)) / (m - 1)
			сvectors[i][j] = сvectors[j][i] = covariance

	return сvectors

In [106]:
calculate_covariance_matrix(vectors)

[[1.0, 1.0], [1.0, 1.0]]

# Linear Regression Using Normal Equation
Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

In [107]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [108]:
import numpy as np
def linear_regression_normal_equation(X, y):
    X, y = np.array(X), np.array(y)
    theta = np.round(((np.linalg.inv(X.T@X))@X.T@y), 3)
    return theta

In [109]:
linear_regression_normal_equation(X,y)

array([-0.,  1.])

# Linear Regression Using Gradient Descent
Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.

In [110]:
import numpy as np

X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
alpha = 0.01
iterations = 1000

In [111]:
def linear_regression_gradient_descent(X: np.ndarray, y: np.ndarray, alpha: float, iterations: int) -> np.ndarray:

	m, n = X.shape
	theta = np.zeros((n, 1))

	for iter in range(iterations):
		preds = X @ theta
		error = preds - y.reshape(-1,1)

		upd = X.T @ error / m
		
		theta -= alpha*upd
	
	theta = np.round(theta.flatten(), 4)
	return theta

In [112]:
linear_regression_gradient_descent(X, y, alpha, iterations)

array([0.1107, 0.9513])

# Feature Scaling Implementation
Write a Python function that performs feature scaling on a dataset using both standardization and min-max normalization. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. It should return two 2D NumPy arrays: one scaled by standardization and one by min-max normalization. Make sure all results are rounded to the nearest 4th decimal.



In [113]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])

In [114]:
def feature_scaling(data: np.ndarray) -> (np.ndarray, np.ndarray):

	standardized_data = (data - data.mean(axis = 0)) / data.std(axis = 0)
	normalized_data = ((data - data.min(axis = 0))/ (data.max(axis = 0) - data.min(axis = 0)))

	return np.round(standardized_data, 4), np.round(normalized_data ,4)

In [115]:
feature_scaling(data)

(array([[-1.2247, -1.2247],
        [ 0.    ,  0.    ],
        [ 1.2247,  1.2247]]),
 array([[0. , 0. ],
        [0.5, 0.5],
        [1. , 1. ]]))

# Sigmoid Activation Function Understanding

Write a Python function that computes the output of the sigmoid activation function given an input value z. The function should return the output rounded to four decimal places.

In [116]:
z = 0

In [117]:
import math

def sigmoid(z: float) -> float:
	sigma = 1 / (1+math.exp(-z))
	return round(sigma, 4)

In [118]:
sigmoid(z)

0.5

# Softmax Activation Function Implementation
Write a Python function that computes the softmax activation for a given list of scores. The function should return the softmax values as a list, each rounded to four decimal places.

In [119]:
scores = [1, 2, 3]

In [120]:
import math

def softmax(scores: list[float]) -> list[float]:
	expo = [math.exp(x) for x in scores]
	summary = sum(expo)

	pred = [round(expo[i] / summary,4) for i in range(len(expo))]
	return pred

In [121]:
softmax(scores)

[0.09, 0.2447, 0.6652]

# Batch Iterator for Dataset
Implement a batch iterable function that samples in a numpy array X and an optional numpy array y. The function should yield batches of a specified size. If y is provided, the function should yield batches of (X, y) pairs; otherwise, it should yield batches of X only.

In [122]:
import numpy as np

X = np.array([[1, 2], 
              [3, 4], 
              [5, 6], 
              [7, 8], 
              [9, 10]])

y = np.array([1, 2, 3, 4, 5])

batch_size = 2

In [123]:
def batch_iterator(X, y, batch_size):
    
    samples = X.shape[0]
    batches = []

    for i in np.arange(0, samples, batch_size):
        begin, end = i, min(i+batch_size, samples)
        
        if y is not None:
            batches.append([X[begin:end], y[begin:end]])
        else:
            batches.append(X[begin:end])

    return batches

In [124]:
batch_iterator(X, y, batch_size)

[[array([[1, 2],
         [3, 4]]),
  array([1, 2])],
 [array([[5, 6],
         [7, 8]]),
  array([3, 4])],
 [array([[ 9, 10]]), array([5])]]

# Calculate Accuracy Score
Write a Python function to calculate the accuracy score of a model's predictions. The function should take in two 1D numpy arrays: y_true, which contains the true labels, and y_pred, which contains the predicted labels. It should return the accuracy score as a float.

In [125]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 0, 1, 0, 1])

In [126]:
def accuracy_score(y_true, y_pred):
	a = 0
	for i in range(len(y_true)):
		if y_true[i] == y_pred[i]:
			a+=1
	
	accuracy_score = a / len(y_true)
	return accuracy_score

In [127]:
accuracy_score(y_true, y_pred)

0.8333333333333334

# Implementation of Log Softmax Function
In machine learning and statistics, the softmax function is a generalization of the logistic function that converts a vector of scores into probabilities. The log-softmax function is the logarithm of the softmax function, and it is often used for numerical stability when computing the softmax of large numbers.

Given a 1D numpy array of scores, implement a Python function to compute the log-softmax of the array.

In [128]:
import numpy as np

A = np.array([1, 2, 3])

In [129]:
def log_softmax(scores: list) -> np.ndarray:
	scores = scores-max(scores)
	return scores - np.log(np.sum(np.exp(scores)))

In [130]:
log_softmax(A)

array([-2.40760596, -1.40760596, -0.40760596])